consumes:
  - application/io.goswagger.examples.todo-list.v1+json
info:
  description: From the todo list tutorial on goswagger.io
  title: A Todo list application
  version: 1.0.0
produces:
  - application/io.goswagger.examples.todo-list.v1+json
schemes:
  - http
swagger: "2.0"
definitions:
  item:
    type: object
    required:
      - description
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      description:
        type: string
        minLength: 1
      completed:
        type: boolean
        default: false
        description: Is this task completed?
  error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
paths:
  /:
    get:
      tags:
        - todos
      operationId: findTodos
      responses:
        200:
          description: list the todo operations
          schema:
            type: array
            items:
              $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - todos
      operationId: addTodo
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"

  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    put:
      tags: ["todos"]
      operationId: updateTodo
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/item"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - todos
      operationId: deleteTodo
      responses:
        204:
          description: "Deleted"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
